import llm_blender
blender = llm_blender.Blender()
blender.loadranker("llm-blender/PairRM") # load ranker checkpoint

inputs_1 = ["hello, how are you!", "I love you!"]
candidates_texts_1 = [["get out!", "hi! I am fine, thanks!", "bye!",'abababababababab'], 
                    ["I love you too!", "I hate you!", "Thanks! You're a good guy!",'ababababababababab']]

# [ 2.334010601043701, -0.5431278347969055, -2.559659719467163, 0.8123722076416016, -0.04359527677297592 ]
# [ -1.8113014698028564, 6.7491254806518555, -4.6721954345703125, -8.895726203918457, 8.630096435546875 ]
# [ -0.006333255674690008, 0.02024930715560913, 0.7605324983596802, 0.008183526806533337, -0.782632052898407 ]
# [ 0.9246727228164673, 0.68443763256073, 1.5777795314788818, -3.5300097465515137, 0.34311988949775696 ]
inputs=["Can you summarize the 2-hour event in a few sentences? Generate according to: There was a lot of laughter and hilarity during our 2hr event and at the end they were all so thrilled with what they had achieved. They had learnt a new skill and each created 8 beautiful cupcake works of art to share with their friends and family when they got home. Although they couldn't help but eat one before they left. They couldn't believe how delicious they were!.",
          "Can you deduce the objective and subjective aspects of this sentence - 'The culinary masterpiece provided a tempting experience'? Show your reasoning behind your answer.",
          "Who are you?",
          "Do you have pictures or video of this step?"]
candidates_texts =[["During the 2-hour event, participants enjoyed a lot of laughter and hilarity as they learned a new skill: decorating cupcakes. Each person created eight beautiful and unique works of art to share with their friends and family. Despite their eagerness to take their creations home, they couldn't resist sampling one and were thrilled by their deliciousness.", "During the 2-hour event, participants enjoyed a lot of laughter and hilarity as they learned a new skill: decorating cupcakes. Each person created eight beautiful, unique works of art to share with friends and family. The excitement was palpable at the end, as everyone was thrilled with their accomplishments. Despite their eagerness to share, many couldn't resist sampling one delicious cupcake before leaving.", "During the 2-hour event, participants enjoyed a lot of laughter and hilarity while learning a new skill. They successfully created 8 beautiful cupcake works of art each, which they were thrilled to share with their friends and family. Despite their eagerness to take their creations home, they couldn't resist trying one and were amazed by their delicious taste.", "During the 2-hour event, participants engaged in a fun and laughter-filled experience as they learned a new skill: decorating cupcakes. Each person created eight beautiful, unique works of art to take home and share with friends and family. The excitement was palpable as they marveled at their creations and couldn't resist sampling one, which left them amazed by their deliciousness.", "During the 2-hour event, attendees enjoyed a lot of laughter and hilarity as they learned a new skill: decorating cupcakes. Each participant created eight beautiful and unique works of art to share with friends and family, but they couldn't resist sampling one before leaving and were thrilled by their deliciousness. At the end of the event, everyone was elated with their achievements." ],
[ "Objective aspect: The sentence describes the culinary masterpiece as providing an experience. This is an objective statement because it is a fact that the masterpiece offered an experience.\n\nSubjective aspect: The sentence also implies that the experience was tempting. This is a subjective statement because tempting is a subjective experience and can vary from person to person. One person may find the experience of the culinary masterpiece tempting, while another person may not. Therefore, the sentence contains both objective and subjective elements.", "Objective aspect: A culinary masterpiece is an objective fact - it is a dish that has been skillfully prepared and presented. The use of the word \"provided\" also implies an action that has taken place, which is objective.\n\nSubjective aspect: The word \"tempting\" is subjective, as it implies a personal experience or feeling. Different people may find different dishes tempting, and what one person finds tempting may not be the same for another person. Therefore, the subjective aspect of the sentence lies in the experience of being tempted, which varies from person to person.", "Objective aspect: A culinary masterpiece is an objective fact. It refers to a dish that has been skillfully prepared and presented, often using high-quality ingredients and intricate cooking techniques.\n\nSubjective aspect: The tempting experience is a subjective interpretation. It suggests that the person who ate the culinary masterpiece found it appealing, enticing, or irresistible. The experience of being tempted is a personal and subjective feeling, and it can vary greatly from person to person.", "Objective aspect: A culinary masterpiece is an objective fact. It refers to a dish or meal that has been skillfully prepared and presented. It can be verified by anyone who experiences it.\n\nSubjective aspect: The word \"tempting\" is subjective. It implies that the person experiencing the culinary masterpiece found it appealing or irresistible. Different people may have different reactions to the same dish, so what is tempting to one person may not be the same for another. Therefore, the experience of the culinary masterpiece being tempting is subjective.\n\nSo, the objective aspect of the sentence is \"The culinary masterpiece provided an experience,\" and the subjective aspect is \"a tempting experience.\"", "Objective aspect: A culinary masterpiece is an objective fact. It refers to a dish that has been skillfully prepared and presented. It is something that exists and can be observed.\n\nSubjective aspect: The tempting experience is subjective. It refers to the sensation or feeling one has when encountering the culinary masterpiece. Tempting means provoking desire or interest, and this response can vary from person to person depending on their individual preferences and appetites. Therefore, the tempting experience is a subjective interpretation of the culinary masterpiece." ],
[ "I'm an artificial intelligence designed to assist with various tasks and answer questions to the best of my ability. I don't have the ability to have a personal identity or emotions. I'm here to help you! How can I assist you today?", "I am a large language model developed by Mistral AI. I am designed to generate human-like text based on the input I receive. I don't have the ability to have a personal identity or emotions. I'm here to help answer questions, generate creative text, and assist with various tasks to the best of my ability.", "I am a large language model developed by Mistral AI. I am designed to assist with various tasks by processing and generating human-like text based on the input I receive. I don't have the ability to have a personal identity or emotions. I'm here to help answer questions, generate creative content, and provide information to the best of my ability. How can I assist you today?", "I am a large language model developed by Mistral AI. I am designed to generate human-like text based on the data I've been trained on. I don't have the ability to have experiences or emotions, but I can process text and generate responses based on that text. I'm here to help answer questions, generate creative text, and assist with various tasks. How can I help you today?", "I am a large language model developed by Mistral AI. I am designed to generate human-like text based on the data I've been trained on. I don't have the ability to have feelings, emotions, or a physical presence. I exist solely to process and generate text. I'm here to help answer questions, generate creative text, and assist with various tasks that involve language processing." ],
[ "I'm an AI language model and I don't have the ability to take or possess pictures or videos. However, I can help guide you through the process with detailed instructions. If you're referring to a specific DIY project or tutorial, feel free to ask and I'll do my best to provide you with clear and concise steps.", "I'm an AI language model and don't have the ability to take or have access to pictures or videos. However, I can guide you through the process with detailed instructions if you have a specific home repair or DIY project in mind. If you're looking for visual aids, I recommend checking out home improvement websites or YouTube channels for tutorials on the topic.", "I'm an AI language model and don't have the ability to take or have access to pictures or videos. However, I can describe the steps in detail or guide you to resources where you may find visual content. If you're asking about a specific DIY project or process, feel free to provide some more context or details and I can try to help you with that.", "I'm an AI language model and don't have the ability to take or have access to pictures or videos. However, I can describe the steps in detail or guide you to online resources where you may find visual instructions. For instance, if you're asking about a specific cooking recipe, you can search for that recipe on a trusted food website or YouTube channel for visual instructions. If you could please provide more context or details about what step you're referring to, I'd be happy to help explain it further.", "I'm an AI language model and don't have the ability to take or have access to pictures or videos. However, I can describe the steps in detail with text. If you're referring to a specific DIY project or process, I'd be happy to help explain it in detail with clear instructions. For example, if you're asking about a home improvement project, I can tell you what tools and materials you'll need, the steps to take, and any potential challenges you might encounter. Just let me know what you have in mind!" ]]
ranks = blender.rank(inputs, candidates_texts, return_scores=False, batch_size=1)
print('The Rank:') 
print(ranks)
scores = blender.rank(inputs, candidates_texts, return_scores=True, batch_size=1)
print('All Rewards:') 
print(scores)
# ranks is a list of ranks where ranks[i][j] represents the ranks of candidate-j for input-i
"""
ranks -->
array([[3, 1, 2], # it means "hi! I am fine, thanks!" ranks the 1st, "bye" ranks the 2nd, and "get out!" ranks the 3rd. 
       [1, 3, 2]], # it means "I love you too"! ranks the the 1st, and "I hate you!" ranks the 3rd.
       dtype=int32) 

"""

rewards = blender.rank_with_ref(inputs, candidates_texts, return_scores=True, batch_size=1,mode='shortest')
print('All Rewards:') # rewards of all candidates for all inputs
print(rewards)
rewards = blender.rank_with_ref(inputs, candidates_texts, return_scores=True, batch_size=1,mode='first')
print('All Rewards:') # rewards of all candidates for all inputs
print(rewards)
